name = input("escreva algo: ")
print("o tipo primitivo desse algo é",(type(name)))
print("só tem espaços?", name.isspace())
print("só tem letras?", name.isalpha())
print("é alphanumerico?", name.isalnum())
print("é um decimal?",name.isdecimal())
print("esta em maiusculo?", name.isupper())
print("esta em minusculo?", name.islower())
print("esta capitalizado?", name.istitle())